<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>StardewChaos</AssemblyName>
    <RootNamespace>StardewChaos</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Version>1.0.0</Version>
    <EnableHarmony>true</EnableHarmony>
    <EnableModDeploy>true</EnableModDeploy>
    <EnableModZip>true</EnableModZip>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

</Project>